### ISSUE TITLE
Associate the async service to the TaskExecutor 

### ISSUE THREAD

**Issue by duntzer** [spring-guides/gs-async-method#12]
I think this example misses the association between the task executor and the service in an unfortunate way, i.e. how this is being set up (quote from the Javadoc): "By default, Spring will be searching for an associated thread pool definition: either a unique TaskExecutor bean in the context, or an Executor bean named "taskExecutor" otherwise. If neither of the two is resolvable, a SimpleAsyncTaskExecutor will be used to process async method invocations."

I think it could be beneficial for this guide, and for the possibility of using this code as a template, to add an explicit association between the executor and the async service by naming the executor bean and specifying the name of if in the @Async annotation. 

Otherwise I think it would be good to rename the the Executor bean to the expected name "taskExecutor"

**Comment by dsyer** [comment]
The javadocs you are quoting must be wrong (or the wrong ones) then, right, because the app works and you can tell from the logs that it is using the provided `Executor`? Where did you find that exactly?

**Comment by duntzer** [comment]
so this is what I'm proposing could be used instead: https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#scheduling-annotation-support-qualification

**Comment by dsyer** [comment]
That makes sense. We could just use the fallback name "taskExecutor". I think I would prefer that, and an explanation of why it's a good idea. Do you want to propose a change?

**Comment by duntzer** [comment]
ok sounds good, I'll do that!

**Comment by dsyer** [comment]
Fixed via #13
