### ISSUE TITLE
Example fails with HTTP status code 400 (Bad Request)

### ISSUE THREAD

**Issue by jayho** [spring-guides/gs-async-method#4]
Running the example throws the following exception:
`org.springframework.web.client.HttpClientErrorException: 400 Bad Request`

The reason is that Facebook's Graph API requires an access token for these requests.

Suggestion: Use (e.g.) Github's API by changing the requests generated from
* http://graph.facebook.com/PivotalSoftware
* http://graph.facebook.com/CloudFoundry
* http://graph.facebook.com/SpringFramework

to

* https://api.github.com/users/PivotalSoftware
* https://api.github.com/users/CloudFoundry
* https://api.github.com/users/Spring-Projects

Happy to provide a pull request if desired.

**Comment by gregturn** [comment]
PR sounds great. Thanks!
