### ISSUE TITLE
Use CompletableFuture instead of Future

### ISSUE THREAD

**Issue by altfatterz** [spring-guides/gs-async-method#7]
See pull request: https://github.com/spring-guides/gs-async-method/pull/6

**Comment by gregturn** [comment]
Why is there an issue opened with no details followed by a PR also with a lack of details?

**Comment by dsyer** [comment]
Probably worthwhile to read the README change. I think the API is nicer. I don't know about if we need to tak about Guava (in fact I would take that bit out), but it looks like a sensible change to me (given that Java 8 is standard and spring didn't support CompletableFuture when we first published the guide).

**Comment by gregturn** [comment]
I would definitely drop any references to Guava. As for Future vs. CompleteableFuture, if this is the proper path, we should look for ALL guides possibly using Future, and ensure they are updated similarly, so we can remain cohesive.

**Comment by gregturn** [comment]
Cursory scan shows this to be the only such guide.

**Comment by gregturn** [comment]
Duplicates efforts on #6
